### ISSUE TITLE
[Compat] sys/types.h not included

### ISSUE THREAD

**Issue by forflo** [esa-tu-darmstadt/tapasco#114]
Hello Everyone,

[Here](https://github.com/esa-tu-darmstadt/tapasco/blob/df2d9f9eda9793bab72892860ad8b3ddba98e593/runtime/platform/include/platform_types.h#L24), `sys/types.h` is not included. This is not an issue for GCC-compatible compilers as their default mode of operation is `-std=gnu11`. For [POSIX and -std=c11](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html) compliance, including `sys/types.h` is required for code using `ssize_t` ([POSIX_ME_HARDER](https://www.gnu.org/prep/standards/html_node/Non_002dGNU-Standards.html) :sweat_smile:).

Adding a single `-std=c11` already breaks builds depending on `platform_types.h`.

Best regards

**Comment by jahofmann** [comment]
Good catch, thanks! I'll add a fix tomorrow.

Best,
