### ISSUE TITLE
addressmap::get_num_slots() is dead code

### ISSUE THREAD

**Issue by forflo** [esa-tu-darmstadt/tapasco#118]
Hi Everyone,

~I just noticed that [get_num_slots()](https://github.com/esa-tu-darmstadt/tapasco/blob/10c12d5f0d68c34061b094be65ec72d4772e5db6/toolflow/vivado/platform/common/addressmap.tcl#L38) refers to an invalid path if branch develop is checked out. Since TCL's `open` function produces an error if the path given to it cannot be found and since my compositions so far have succeeded, it is very likely that `get_num_slots()` is never called anymore.~ Reason of the cross out: I failed to notice that `TAPASCO_RUNTIME_HOME` refers to the runtime subdirectory...

However, a recursive grep from within the directory root of the develop branch shows:

```sh
$ grep get_num_slots -r
=> vivado/platform/common/addressmap.tcl:  proc get_num_slots {} {
```

Should it be kept for later usage?

Best regards

**Comment by sommerlukas** [comment]
The dead code was removed as part of #135.
