### ISSUE TITLE
Interconnect in group "out_0" named differently depending on number of IPs in the design

### ISSUE THREAD

**Issue by forflo** [esa-tu-darmstadt/tapasco#119]
Hi everyone,

during tapasco::arch create, the composition builds the `out_0` group. Therein, it instantiates an interconnect tree in order to route the target ip AXI masters to the MIG. In case where only one target ip is present in subgroup `arch`, the interconnect is named `bic` instead of `ic_<3-digit-number>`.

Is there a TCL procedure that can be used to query the name of the root of the interconnect tree?

Suggestion (if not):

Rename `bic` into `ic_000`. This will simplify plugin code relying on Vivado's `get_bd_cells -filter ...` function.

Best regards

**Comment by cahz** [comment]
There is currently not a function to find out the root, as this also depends on whether it is a slave or master tree. Normally, the root should be the port provided by the platform.

I have now changed the naming according to your suggestion.
