### ISSUE TITLE
Feature: System Cache

### ISSUE THREAD

**Issue by sommerlukas** [esa-tu-darmstadt/tapasco#14]
(Re-)Implement `Feature` for _Xilinx System Cache_
- [ ] Check datasheet: Write-through strategy?
- [ ] TCL integration

**Comment by cahz** [comment]
According to the datasheet, the strategy is write-back. 

At the moment, the feature is working for all PCIe-based systems. Documentation is available in the [feature documentation](../blob/master/documentation/tapasco-features.md#cache).

Suggested improvements:
- [ ]  Extract feature as a plugin
- [ ]  Support all platforms

**Comment by sommerlukas** [comment]
Support for the system cache will be limited to PCIE-based platforms.

**Comment by cahz** [comment]
Plugin-based version in #147, new platforms can be added as needed.
