### ISSUE TITLE
Prepare Release 2019.10

### ISSUE THREAD

**Issue by jahofmann** [esa-tu-darmstadt/tapasco#150]
- [x] Finish #121 
- [x] Finish #90 
- [x] Finish #80 
- [x] Finish #47 

Afterwards:

- [x] Prepare Release Branch
- [x] Update version specifiers & Check Readme Downloadlinks
- [x] Test Pynq Bitstream Generation
- [x] Test Zedboard Bitstream Generation
- [x] Test VC709 Bitstream Generation
- [x] Test VC709 Default Tools (memcheck, benchmark, debug, arrayinit, arraysum, arrayupdate)
- [x] Add VC709 benchmark file
- [x] Test ZC706 Bitstream Generation
- [x] Test ZC706 Default Tools (memcheck, benchmark, debug, arrayinit, arraysum, arrayupdate)
- [x] Add ZC706 benchmark file
- [x] Test NetFPGA SUME Bitstream Generation
- [x] Test NetFPGA SUME Default Tools (memcheck, benchmark, debug, arrayinit, arraysum, 
arrayupdate)
- [x] Add NetFPGA SUME benchmark file
- [x] Test AU250 Bitstream Generation
- [x] Test ZCU102 Bitstream Generation
- [x] Plot benchmarks

**Comment by jahofmann** [comment]
@cahz and @lukasmweber How long do you need to complete the assigned issues? Need any help?

**Comment by jahofmann** [comment]
I did the ZC706 test already and will test the NetFPGA SUME tomorrow.

**Comment by jahofmann** [comment]
Release Branch created

**Comment by lukasmweber** [comment]
I will start with testing Pynq and Zedboard Bitstream generation.

**Comment by jahofmann** [comment]
VC709 Benchmark added

Renamed to .log because gitlab doesn't like other file types...

[mountdoom_vc709.benchmark.log](https://github.com/esa-tu-darmstadt/tapasco/files/3858085/mountdoom_vc709.benchmark.log)

**Comment by cahz** [comment]
ZC706 Benchmark

[zc706.benchmark.log](https://github.com/esa-tu-darmstadt/tapasco/files/3858121/zc706.benchmark.log)

**Comment by jahofmann** [comment]
Plotted the benchmarks and added a script for the future (Improvements needed)

[performance.pdf](https://github.com/esa-tu-darmstadt/tapasco/files/3858462/performance.pdf)

**Comment by jahofmann** [comment]
For the next time we have to properly specify what kind of bitstreams we're using. Otherwise the benchmarks aren't really comparable.

For my benchmarks I've been using 32 Counter @ 250MHz on a Ryzen 1600x.

**Comment by cahz** [comment]
As discussed last week, I used a bitstream with two counters on the ZC706.

**Comment by jahofmann** [comment]
Release Notes
--------------------
Any input @lukasmweber @cahz @sommerlukas?

------------

We are happy to announce TaPaSCo 2019.10 coming right to you with a number of structural changes.

Directory Structure
===============
The directory structure has been changed completely. The individual parts of TaPaSCo are now separated into the Toolflow and Runtime directories to avoid confusion.

TaPaSCo Setup
============
The novel `tapasco-init` script enables out-of-tree builds to simplify using multiple TaPaSCo builds in parallel.

Toolflow Changes
=======================
The toolflow is now built by Gradle instead of SBT. Along with these changes, we now provide OS packages for leading Linux distributions. Compilation of TaPaSCo is now longer necessary for a majority of users.

Quality of Life
===========
A number of quality of life changes targets the usability of TaPaSCo. For instance, the Readme is updated and should be much clearer.

TaPaSCo Status Core
=================
The status core is now based on Protobuf instead of using a custom format. The new format is much more flexible and provides much more indepth information about the bitstream.

Bugfixes
=======
In total this release closes 34 [Issues](https://github.com/esa-tu-darmstadt/tapasco/issues?q=is%3Aissue+milestone%3A2019.10+is%3Aclosed) in over 270 commits.

**Comment by jahofmann** [comment]
Results for NetFPGA Sume on i5-6600K
There is some issue with the latency measurements (negative measurements)
[netfpga_sume.benchmark.log](https://github.com/esa-tu-darmstadt/tapasco/files/3863093/netfpga_sume.benchmark.log)
 which I have to fix before continuing.
