### ISSUE TITLE
Make "compose finished" messages more generic

### ISSUE THREAD

**Issue by m-ober** [esa-tu-darmstadt/tapasco#156]
Currently, this is the message for a finished compose run:

> [05:14:28 <pool-1-thread-1: ComposeTask> INFO] compose run [counter x 128]@100.000 MHz for axi4mm@aws finished, result: Success, bitstream file: '/scratch/mio/tapasco_f1/compose/axi4mm/aws/counter/128/100.0/axi4mm-aws--counter_128--100.0.bit', logfile: '/scratch/mio/tapasco_f1/compose/axi4mm/aws/counter/128/100.0/axi4mm-aws--counter_128--100.0.log', utilization report: '/scratch/mio/tapasco_f1/compose/axi4mm/aws/counter/128/100.0/utilization.txt', timing report: '/scratch/mio/tapasco_f1/compose/axi4mm/aws/counter/128/100.0/timing.txt'

Notice the `bitstream file` and the `axi4mm-aws--counter_128--100.0.bit` part. Not all platforms generate bitstream files when finished, for example the wording for the AWS F1 would be much better like this:

> Success, Amazon FPGA Image: '[...]/axi4mm-aws--counter_128--100.0.tar'

At least the file extension should be configurable per platform (maybe in `platform.json`?), otherwise Tapasco points the user to a file which does not exist, which might be confusing.

**Comment by sommerlukas** [comment]
The support for this was added in #173;

@m-ober: You can now use that feature for the AWS F1 platform;
