### ISSUE TITLE
tapasco explore fails - illegal vivado project path

### ISSUE THREAD

**Issue by c-93** [esa-tu-darmstadt/tapasco#161]
`tapasco --maxTasks 3 explore ["orca_pe_dexie_512" x 1] @ 260 MHz in frequency -p zc706 --basePath orca_dse`

leads to the following illegal path:
`DSE_axi4mm-zc706-[orca_pe_dexie_512_x_1]_2019-12-18T13-43-25.47939/bd/axi4mm/zc706/orca_pe_dexie_512/001/255.0/timing.txt:`

instead, the path could/ should look like this (no parenthesis):
`DSE_axi4mm-zc706-orca_pe_dexie_512_x_1_2019-12-18T13-43-25.47939/bd/axi4mm/zc706/orca_pe_dexie_512/001/255.0/timing.txt:`

Workaround: Specify path manually:
tapasco --maxTasks 3 explore ["orca_pe_dexie_512" x 1] @ 260 MHz in frequency -p zc706 --basePath orca_dse

**Comment by sommerlukas** [comment]
Fixed by #167.
