### ISSUE TITLE
HBM Adressing

### ISSUE THREAD

**Issue by jojowi** [esa-tu-darmstadt/tapasco#180]
When connecting multiple PEs to the HBM, only one can correctly access it's HBM memory block.
This is because the adresses of the HBM blocks do not all start at 0. Instead all HBM blocks together form a continous address space.
TaPaSCo should automatically offset the addresses of each PE to the address range of the HBM block it is connected to. Then the address space the PEs "see" always starts at 0.

**Comment by jahofmann** [comment]
Related to #181
