### ISSUE TITLE
Move version information to one location

### ISSUE THREAD

**Issue by jahofmann** [esa-tu-darmstadt/tapasco#197]
As commit 8487d8dff9c81b312b91ed2caa8b8972308dc51d shows, updating to a new Version requires modifications in a lot of locations.

Moving this to one file reduces a chance for errors. Considering the heterogeneous locations, this might not be trivial, however.

**Comment by sommerlukas** [comment]
Given the heterogeneity of the programming languages in the project, the different build systems for the different components (Gradle, CMake, ...) and the fact that changes are only required in 5 files, we won't pursue this further.
