### ISSUE TITLE
Detect WPWS timing violation

### ISSUE THREAD

**Issue by cahz** [esa-tu-darmstadt/tapasco#209]
Tapasco currently does not consider negative pulse width slack as a timing violation. This can produce bitstreams which do not meet the timing constraints.

**Comment by hanna-kruppe** [comment]
`tapasco compose [arrayinit x 1] @350MHz -p ultra96v2` with release 2020.04 (in particular, without fix for #205) reproduces this. Timing report: https://gist.github.com/hanna-kruppe/9c679b06ca45091a522e688416adc251

**Comment by sommerlukas** [comment]
Fixed in #232 and #214.
