### ISSUE TITLE
Remove platform zcu102revd

### ISSUE THREAD

**Issue by cahz** [esa-tu-darmstadt/tapasco#217]
As the platform is not supported in standard vivado versions, this results in unnecessary warnings/errors when doing e.g. ´hls´ without stating a platform. In my opinion we should remove it from TaPaSCo.

**Comment by jahofmann** [comment]
Should be okay. We still have one of the ES ZCU102, but as you correctly stated, it's quite annoying to use. Generating the necessary kernel etc is even more of a hassle...

**Comment by cahz** [comment]
There isn't much configuration required anyway, so it's easy to recreate it if needed. 

@jojowi is there any use of the SFP-Plugin? Or is it obsolete after your refactoring?

**Comment by jahofmann** [comment]
There is no use of it anymore if @jojowi supports it... that's still my ancient hacky version.
