### ISSUE TITLE
DSE does not consider features

### ISSUE THREAD

**Issue by cahz** [esa-tu-darmstadt/tapasco#255]
When enabling features on the command line, they are not utilized within design-space-exploration. This produces wrong results of a DSE.

**Comment by dattran96** [comment]
I also found this bug today. Is this issue resolved already?

**Comment by cahz** [comment]
This is still an open issue.

**Comment by dattran96** [comment]
Thanks a lot !

**Comment by cahz** [comment]
Is there any progress on this @lukasmweber?
