### ISSUE TITLE
[Question] Why are the build processes for the kernel module and the rust runtime so tightly coupled?

### ISSUE THREAD

**Issue by forflo** [esa-tu-darmstadt/tapasco#267]
Hi everyone!

In our setup we use separate environments for bitstream tests
and for bitstream builds. In our build environment we only really want 
to have the tapasco kernel module installed.

How does one only create the tapasco kernel without the runtime?

Best regards.

**Comment by jahofmann** [comment]
Hi,

I guess you're referring to the `tapasco-build-libs` script?

To build the kernel module alone you might want to check the gitlab CI script for inspiration: `cd runtime/kernel; make (release)`.

We also provide prebuild kernel modules for a variety of distributions. Check the Readme for links (right at the bottom).
