### ISSUE TITLE
Crash after cancelling TaPaSCo-Job

### ISSUE THREAD

**Issue by wirthjohannes** [esa-tu-darmstadt/tapasco#270]
Steps to reproduce:
 - Start program with long running TaPaSCo-Job
 - Cancel program while job is running
 - Run program again -> Crash (in this case the VM)
For me this happens most of the time (but not always). The crash sometimes occurs directly at program start, sometimes the first few output lines still get processed (number of PEs, ...) and it crashes afterwards. But the crash always occurs **before** the second program run starts a TaPaSCo-Job.

The dmesg output when building TaPaSCo with driver_debug

[dmesg_output.txt](https://github.com/esa-tu-darmstadt/tapasco/files/6100933/dmesg_output.txt)
![dmesg_output](https://user-images.githubusercontent.com/9122706/110313402-a87f3480-8006-11eb-81ac-2086ef928f9b.png)

**Comment by cahz** [comment]
I can further refine this error: it happens when you cancel a running execution and the interrupt comes at a later point in time. The next execution of the host application crashes the system.

**Comment by jahofmann** [comment]
This seems to be a problem where the application is not attached to the driver anymore but the eventfd signal is not properly invalidated/checked for invalidation. Specifically the problem should be at https://github.com/esa-tu-darmstadt/tapasco/blob/8b21b7fa7d0c4142402554425b5b9b337d45d20f/runtime/kernel/pcie/pcie_irq.c#L53

A check for 0 of the eventfd should fix the issue.
