### ISSUE TITLE
Probably bug in ip.tcl

### ISSUE THREAD

**Issue by forflo** [esa-tu-darmstadt/tapasco#294]
https://github.com/esa-tu-darmstadt/tapasco/blob/8b21b7fa7d0c4142402554425b5b9b337d45d20f/toolflow/vivado/common/ip.tcl#L539

This line blows up when I enter a composition with more than eight different PEs. (For example `[ pe0 x 1, pe1 x 1, ..., pe8 x 1 ]`.

For `target_ip_08` the `regsub` command will expand to "08" wich will then be fed into `format`, which in turn will error out with `expected integer but got "08"`.

**Comment by forflo** [comment]
In `develop` the same snippet is here: https://github.com/esa-tu-darmstadt/tapasco/blob/466467a2f4da08f9ff4535e6103942066b9f6ecf/toolflow/vivado/common/ip.tcl#L539

**Comment by cahz** [comment]
Thanks for pointing this out. Leading zeros are treated as octal numbers in tcl...

Will push a fix in a few minutes.
