### ISSUE TITLE
MakeOutOnly does not work on Ultra96 with ALARM

### ISSUE THREAD

**Issue by Markussha** [esa-tu-darmstadt/tapasco#341]
# Description

Using MakeOutOnly on Ultra96 leads to the buffer not being written. Using a current release of Arch Linux for ARM and Linux-XLNX 5.15.

# Expected Behaviour

The buffer should be writeable from the PE.

# Workaround

Use a wrapped pointer that was not passed througn makeOutOnly.

**Comment by tsmk94** [comment]
The SMMU mapping is currently created in the ```copy_to()``` function, which is, however, not called in case ```makeOutOnly``` is in use. Creating the SMMU mapping during "allocating" the memory should fix this issue.

**Comment by tsmk94** [comment]
Fixed in ```develop``` branch
