### ISSUE TITLE
SVM of Multi-FPGAs? 

### ISSUE THREAD

**Issue by KC-Kevin** [esa-tu-darmstadt/tapasco#361]
Hi, 

I am wondering where is the code for SVM of multi-FGPAs? In FPL'22 paper (Direct Device-to-Device Physical Page Migrations
in Multi-FPGA Shared Virtual Memory Systems), it says that the code is going to be open sourced here. However, it seems that there is only code for SVM of a single FPGA between host and device. 
 
@jopperm @jahofmann @sommerlukas @hanna-kruppe @jkorinth 

Thanks!

**Comment by tsmk94** [comment]
Hi @KC-Kevin,

you can find the corresponding code already on our develop-branch. It will be merged into master in our next release.

Best regards
