### ISSUE TITLE
Include Scala-based tools in OS-packages

### ISSUE THREAD

**Issue by sommerlukas** [esa-tu-darmstadt/tapasco#40]
Identify a reliable way to include the Scala-based tools (`tapasco` CLI-tool and `itapasco`) in the `.deb`/`.rpm`-packages. 

All necessary dependencies should also be packaged.

**Comment by jahofmann** [comment]
We should maybe separate Tapasco and Tapasco-Runtime a bit better as well... will open a new issue for that

**Comment by sommerlukas** [comment]
I checked our options here and took a look at what SBT-plugins (specifically [sbt-native-packager](https://www.scala-sbt.org/sbt-native-packager/)) can provide. 
IMHO, there's two options here: 
* Packaging only the actual Scala part into an OS-package and require the user to have all the other stuff necessary for composing (TCL, etc.) somewhere else, referenced by $TAPASCO_HOME
* Include all the necessary stuff, TCL-scripts, etc. in the OS-package. 

In the first case, the OS-package wouldn't be very useful. In the latter case, the functionality provided by SBT-plugins needs to be extended. If we go for this option, I would delay this feature until we have separated the directories as discussed in #56, i.e. until release 2019.10.

@jahofmann, @cahz: What do you think?

**Comment by sommerlukas** [comment]
Delaying this until we have restructured directories according to #56.
