### ISSUE TITLE
Asynchronous Memory Transfers

### ISSUE THREAD

**Issue by sommerlukas** [esa-tu-darmstadt/tapasco#5]
From @jkorinth: Similar to asynchronous job launches: Check if asynchronous memory transfers could be useful. I guess probably not so much, because we need to wait for the transfers to finish, before we can launch the job in anycase - worst/ideal case would be that the job starts immediately and data must be available. It would be possible to add mem barriers based on the job struct, but I do not think this would be worth the effort.

**Comment by jahofmann** [comment]
This has already been addressed.
