### ISSUE TITLE
DSE: Delete projects for failed runs.

### ISSUE THREAD

**Issue by yannickl96** [esa-tu-darmstadt/tapasco#53]
TaPaSCo should delete the projects of failed compositions in the DSE so the file system is not filling up with junk.

**Comment by jkorinth** [comment]
I think there has been a command switch for that already, part of the DSE command. It keeps the logs around, but deletes the huge Vivado projects and PnR data.

**Comment by m-ober** [comment]
What if I want to analyze a failed run, e.g. look at the riming report in Vivado?

Maybe it would be good to have a clean-up procedure (platform specific), that removes the bitstream, DCPs and maybe other files.

**Comment by jahofmann** [comment]
You can analyze these issues through simple compose runs. When you go through DSE it is assumed that you have at least done compose runs before and checked that your design performs to your liking.

**Comment by lukasmweber** [comment]
Im currently implementing this functionalit and my take on this is the introduction of a flag `--deleteProjects` for `compose` and `explore` jobs, so that the user can specify whether they want to keep these files (like it is now) or if all project files should be discarded (if the flag is set).

**Comment by sommerlukas** [comment]
The requested functionality was added in #72.
