### ISSUE TITLE
Implement memory testing infrastructure.

### ISSUE THREAD

**Issue by jahofmann** [esa-tu-darmstadt/tapasco#78]
Add simple IP that provides a testing infrastructure for memory performance:
 - Batch Read
 - Batch Write
 - Batch Read/Write (to same or different locations)
 - Random Read
 - Random Write
 - Random Read/Write

Parameters such as size or iterations should be configurable.

**Comment by jahofmann** [comment]
Adding @jojowi as he has the required IP.

**Comment by jojowi** [comment]
I also have an IP for measuring the read latency. Is this also of interest?

**Comment by jahofmann** [comment]
Certainly!
