### ISSUE TITLE
Add 32bit Zynq build for tlkm to CI

### ISSUE THREAD

**Issue by cahz** [esa-tu-darmstadt/tapasco#80]

**Comment by cahz** [comment]
Linux headers from a x86_64 system are not working for this task and the compiler does not find all header files. To be able to cross-compile the kernel module, I have not found a solution without cross-compiling the Linux kernel before. Due to the complexity I wouldn't do this in a CI runner.

**Comment by jahofmann** [comment]
The runtime libraries should be fine, though.

**Comment by cahz** [comment]
Runtime libraries are now in CI (on branch feature/crosscompiling). It would be nice to also detect problems in the kernel module (e.g. fixes in 576ba4068f62095c804e879c4a928fb04431486d).

**Comment by jahofmann** [comment]
I think we can add an extra runner just for running 32 bit applications. This runner would run on a dedicated 32 bit VM. That shouldn't be too difficult.
