### ISSUE TITLE
Cannot override maximum/starting frequency for DSE

### ISSUE THREAD

**Issue by m-ober** [esa-tu-darmstadt/tapasco#98]
For me, the evaluation of an IP core often vastly underestimates the maximum frequency at which the design will run. I mentioned this in #92 and was told that it should be possible to override the frequency:

> The frequency found during OOC synthesis will be used as upper bound for the frequency to limit the design space. You should be able to manually override this start frequency by specifying a frequency just as you would do for a compose job (e.g., @ 400 MHz).

Unfortunately, this does not seem to work, e.g.:

`tapasco --maxThreads 6 --maxTasks 2 explore [NIPS5-Q8.32-18.5 x 1] @ 500 MHz in frequency --platforms aws --deleteProjects true`

Tapasco seems to parse the given frequency, but ignores it:

> Jobs = List(DesignSpaceExplorationJob([NIPS5-Q8.32-18.5 x 1],500.0,(freq),<function3>,12,None,None,Some(ArrayBuffer(aws)),None,None,Some(true)))
> [...]
> [16:31:39 <pool-1-thread-1: ConcreteBatch> INFO] starting [[NIPS5-Q8.32-18.5 x 1]] [F=320.000] for axi4mm@aws            
> [...]

320 MHz is still the frequency found during evaluation.

Overriding the frequency using the proposed way would be a very useful feature.

**Comment by lukasmweber** [comment]
Resolved by #99
